### PR TITLE
Cool stuff

### PR DESCRIPTION
**Pull request by javelinanddart**

### CODE REVIEW

**Comment by easyaspi314** [comment]
+1 for this!
Looks tasty! :yum:

**Comment by easyaspi314** [comment]
Can you build a boot.img for skyrocket (if you don't already have one)?

I'd like to test this.

**Comment by javelinanddart** [comment]
I cannot, as I do not have cm13 source code synced up

**Comment by easyaspi314** [comment]
You don't need it all to make a boot.img. See here: https://wiki.cyanogenmod.org/w/Doc:_integrated_kernel_building

Even if you just get me a zImage, that would be great.
Turns out, that is all that I need.

**Comment by javelinanddart** [comment]
@easyaspi314 K, building a zImage for you now then

**Comment by easyaspi314** [comment]
Thanks!

**Comment by easyaspi314** [comment]
I hope this also fixes hotplugging. Right now on 2/16, hotplugging isn't working correctly.

**Comment by javelinanddart** [comment]
@easyaspi314
zImage: http://downloads.codefi.re/jdcteam/MSM8660/coolstuffzImage
dhd.ko (just in case): http://downloads.codefi.re/jdcteam/MSM8660/coolstuffdhd.ko
I don't know how/why it would fix hotplugging and how/why it broke

**Comment by javelinanddart** [comment]
@easyaspi314 KernelAdiutor official (as of today, version 0.9.9.4) has support for toggling pocket detection, Can you see if it works?
I don't know why it shouldn't but if you can check, please do:
Cover up the sensors at the top of your phone
Try to sweep2wake or doubletap2wake (sleep ones should work fine)

**Comment by easyaspi314** [comment]
:+1: Will test. :smile:

**Comment by easyaspi314** [comment]
The phone booted successfully with the new kernel. I am downloading the new version on Adiutor right now. Do you personally have a Hercules or Skyrocket?
Pocket mode works.
Governors I am trying now. 

Sweet.

**Comment by javelinanddart** [comment]
@easyaspi314 Sweet! and I have hercules

**Comment by easyaspi314** [comment]
If you can deal with the infamous rotation issues, here is the boot.img.

https://drive.google.com/file/d/0Bxk_L8QgNv7TcHRZcE5VNG05bmM/view?usp=sharing

In a terminal:

```
su
dd if=/dev/block/mmcblk0p8 of=/sdcard/boot.img.bak
dd if=/path/to/boot.img of=/dev/block/mmcblk0p8
```

or in TWRP, 
Backup > Check only Boot > Swipe > Home > Install > Images... > select the boot.img > Boot > swipe.
Reboot.

**Comment by easyaspi314** [comment]
And the best part is that governor configs work.

I may just need to look harder to figure out hotplugging. Hmm.

**Comment by javelinanddart** [comment]
@easyaspi314 I'm not on CM13 lol
btw, I am aware how to backup and flash a boot.img, both in TWRP, and via dd ;)
I may flash cm13 later, but atm I'm still rocking cm11, because my hercules is broken af and it constantly soft rebooted each time I turned the screen off on cm12.1/lollipop, so I'm a bit weary to try M
It might be a good idea for me to tune uberdemand oob actually

**Comment by javelinanddart** [comment]
@easyaspi314 What do you mean hotplugging is broken, exactly?

**Comment by easyaspi314** [comment]
@javelinanddart Haha I know.

Sucks that you have a broken Hercules. Though you may want to try CM13. Maybe you can set up MultiRom or something and boot CM11 in CM13. 
I do that on my S3 (d2lte), my DD with debloated TouchWiz and CM11.
I have a broken Skyrocket if it makes you feel better.
- Screen cracked
- Yellowed screen with the lovely blotches
- Sometimes the screen shows weird stripes
- Battery life weary
- Dust in camera
- Tattered case from me prying the case off to try to fix the camera, not noticing the screw under a sticker

I had a *_fun_* time unbricking when trying to flash Bryan's AOSPA-L. Don't get me started. It is a long story.

---

As for hotplugging, it may be the "Auto hotplug" is disabled by default, or something.
So when I use 3C to change CPU settings, usually you long-press online or offline on the second core to get "free" but it snaps back to the previous setting. Weird. 

And trying to set to Power saver profile snaps back too. Hmm.

**Comment by easyaspi314** [comment]
Wait.........
The power save mode thing says this:

`java.lang.SecurityException: package android does not belong to 10019`
when the performance tile crashes...... Hmm...

**Comment by javelinanddart** [comment]
@easyaspi314 Kinda curious, when did hotplugging break/when did you notice it stopped working?

**Pull request merged**
